### ISSUE TITLE
jenkins pipeline test doesn't ensure data is loaded before checking for it

### ISSUE THREAD

**Issue by thoraxe** [openshift-roadshow/nationalparks#2]
The shell script is just a curl to the `all` endpoint, but never involves loading the data into the database. If someone does labs out of order or never loads the data, this test will always fail.

It's also a little odd that the dev and "live" apps are both using the same database, but that's not as big of a concern.

One option would be to modify the test script to hit the `load` before hitting `all`.

@siamaksade

**Comment by siamaksade** [comment]
Should we consider running labs out of order? 

Agree that Live should have its own database if there is no resource constraint anymore.

**Comment by thoraxe** [comment]
SHOULD we run labs out of order? Likely not. But someone might forget something, and it seems odd that the test requires that something else already put in the data.

There's still a resource constraint. But we could perhaps shove a non-prod collection into the same mongo instance?

**Comment by siamaksade** [comment]
If we want to make it more compatible with real scenario then we probably should have two separate mongo instances. Added it with af4ec690be2cf3b47d2e540a04e5d0c4f93a8d83

**Comment by jorgemoralespou** [comment]
If you added a new mongodb, you should also load the data
